### ISSUE TITLE
can't open Example PR adding Airbyte Snowflake connector

### ISSUE THREAD

**Issue by ykuc** [doublecloud/transfer#149]
[proto-model](https://github.com/doublecloud/transfer/tree/7ac9b173d69ef3c5721df9fb4d9f5b6415b4f50d/pkg/providers/airbyte#1-add-proto-model) has [protos](https://a.yandex-team.ru/arcadia/transfer_manager/go/proto/api/endpoint/airbyte/?rev=r10953642)

[docker image and provider type](https://github.com/doublecloud/transfer/tree/7ac9b173d69ef3c5721df9fb4d9f5b6415b4f50d/pkg/providers/airbyte#2-adding-docker-image-and-provider-type) has: [API-Providers enum](https://a.yandex-team.ru/arcadia/transfer_manager/go/proto/api/endpoint.proto?rev=r10968706#L74), [Known Airbyte Providers](https://a.yandex-team.ru/arcadia/transfer_manager/go/pkg/providers/airbyte/provider_model.go?rev=r11073103#L29), proto-model [here](https://a.yandex-team.ru/arcadia/transfer_manager/go/pkg/providers/airbyte/provider_model.go?rev=r11073103#L303), Airbyte-docker image [here](https://a.yandex-team.ru/arcadia/transfer_manager/go/pkg/providers/airbyte/provider_model.go?rev=r11073103#L282), code like we do [here](https://a.yandex-team.ru/arcadia/transfer_manager/go/pkg/providers/airbyte/provider_model.go?rev=r11073103#L351)

[3. Enable new provider](https://github.com/doublecloud/transfer/tree/7ac9b173d69ef3c5721df9fb4d9f5b6415b4f50d/pkg/providers/airbyte#3-enable-new-provider) has use [grants](https://a.yandex-team.ru/arcadia/transfer_manager/go/pkg/grants/?rev=r11099251) mechanism, do [here](https://a.yandex-team.ru/arcadia/transfer_manager/go/pkg/grants/grants.go?rev=r11099251#L67), 

[pr](https://github.com/doublecloud/transfer/tree/7ac9b173d69ef3c5721df9fb4d9f5b6415b4f50d/pkg/providers/airbyte#example-pr-adding-airbyte-snowflake-connector) has [PR](https://a.yandex-team.ru/review/3653374/files/1)

**Comment by laskoviymishka** [comment]
This readme doc is slightly out dated, pobably will fix it.

**Comment by ykuc** [comment]
thx

**Comment by laskoviymishka** [comment]
@ykuc https://github.com/doublecloud/transfer/blob/main/pkg/providers/airbyte/README.md here is a updated readme, plz not that for now there is no real need to add anything airbyte related to codebase.
Everything is configuration-based, any airbyte-compatible docker image would work here.
